In [1]:
import pandas as pd

In [2]:
# Cargamos los datos

data = pd.read_csv("reddit_database_sentiment.csv", sep=";", engine="python")

In [3]:
data.head()

,created_date,created_timestamp,subreddit,title,author,author_created_utc,full_link,score,num_comments,num_crossposts,subreddit_subscribers,post,sentiment
0,2010-02-11 19:47:22,1265910442.0,analytics,So what do you guys all do related to analytic...,xtom,1.227476e+09,https://www.reddit.com/r/analytics/comments/b0...,7.0,4.0,0.0,NaN,There's a lot of reasons to want to know all t...,NEGATIVE
1,2010-03-04 20:17:26,1267726646.0,analytics,"Google's Invasive, non-Anonymized Ad Targeting...",xtom,1.227476e+09,https://www.reddit.com/r/analytics/comments/b9...,2.0,1.0,0.0,NaN,"I'm cross posting this from /r/cyberlaw, hopef...",NEGATIVE
2,2011-01-06 04:51:18,1294282278.0,analytics,"DotCed - Functional Web Analytics - Tagging, R...",dotced,1.294282e+09,https://www.reddit.com/r/analytics/comments/ew...,1.0,1.0,NaN,NaN,"DotCed,a Functional Analytics Consultant, offe...",NEGATIVE
3,2011-01-19 11:45:30,1295430330.0,analytics,Program Details - Data Analytics Course,iqrconsulting,1.288245e+09,https://www.reddit.com/r/analytics/comments/f5...,0.0,0.0,NaN,NaN,Here is the program details of the data analyt...,NEGATIVE
4,2011-01-19 21:52:28,1295466748.0,analytics,potential job in web analytics... need to anal...,therewontberiots,1.278672e+09,https://www.reddit.com/r/analytics/comments/f5...,2.0,4.0,NaN,NaN,i decided grad school (physics) was not for me...,POSITIVE

In [4]:
data.shape

(274239, 13)

In [5]:
data.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 274239 entries, 0 to 274238
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   created_date           274238 non-null  object
 1   created_timestamp      274215 non-null  object
 2   subreddit              274209 non-null  object
 3   title                  274209 non-null  object
 4   author                 274209 non-null  object
 5   author_created_utc     42585 non-null   float64
 6   full_link              274209 non-null  object
 7   score                  274209 non-null  float64
 8   num_comments           274209 non-null  float64
 9   num_crossposts         224727 non-null  float64
 10  subreddit_subscribers  213890 non-null  float64
 11  post                   274209 non-null  object
 12  sentiment              274203 non-null  object
dtypes: float64(5), object(8)
memory usage: 405.7 MB

In [6]:
data.post

0         There's a lot of reasons to want to know all t...
1         I'm cross posting this from /r/cyberlaw, hopef...
2         DotCed,a Functional Analytics Consultant, offe...
3         Here is the program details of the data analyt...
4         i decided grad school (physics) was not for me...
                                ...
274234    Hello! I am wonder how the following output wo...
274235    Can anybody recommend me a book with medical s...
274236    I'm trying to build a simple Markov chain. I h...
274237    How do I view all available Rcpp::plugins? Tha...
274238    Hi everybody,\n\nI am currently doing a factor...
Name: post, Length: 274239, dtype: object

In [7]:
# Cantidad de valores faltantes

data.post.isna().sum()

30

In [8]:
# Análisis general de los posts

data.post.tolist()

["There's a lot of reasons to want to know all this stuff, so I figured I'd get to know the others that are on this subreddit.\n\nSo let's hear it: Webmasters? Coders? Marketers? Work for an analytics software company? You get the idea.",
 'I\'m cross posting this from /r/cyberlaw, hopefully you guys find it as interesting as I did(it deals with Google Analytics):\n\nSo quite awhile ago, I ordered a Papa John\'s pizza online. My job largely involves looking at ads that appear online, so afterwards I was quick to notice *I was getting a LOT* of Papa Johns ads (especially at night) being served through a Google owned company (DoubleClick media). Yesterday one of these ads popped up again on Youtube (a place that typically serves using the adwords program, not doubleclick), so I decided to copy the URL. \n\nFor those not in the advertising field: Making full use of Google\'s analytics tool means that certain information about the advertising campaign is leaked in the URL.\n\nSo let\'s break it apart: \n\n&gt;http://ad.doubleclick.net/click;h=(junk here);~sscs=?http://googleads.g.doubleclick.net/aclk?sa=l&amp;ai=(junk here)&amp;adurl=http://www.papajohns.com/index.shtm?utm_source=googlenetwork&amp;utm_medium=DisplayCPC&amp;utm_campaign=GoogleRemarketing\n\nFirst off, we see ~sscs: ~sscs is doubleclick\'s redirect variable. So rather than directly serving adwords ads, they overrode it to serve through doubleclick, then redirect through what would otherwise be an adwords link(http://googleads.g.doubleclick.net). This is tighter integration than is generally seen with adwords/doubleclick.\n\n* The interesting part is the end variables utm_source=**googlenetwork**&amp;utm_medium=**DisplayCPC**&amp;utm_campaign=**GoogleRemarketing**\n\n* DisplayCPC/googlenetwork - Confirmation that doubleclick is now more finely integrated with adwords.\n\n* "GoogleRemarketing", huh? Let\'s take a look at the definition for "Remarketing"\n\n&gt;Using past campaign information to target a particular message to an audience.\n\nWhile in the past behavioral targetting has largely been based on the sum of your use, this is an interesting(though no doubt more widespread than is known) change in that; explicitly targeting old customers though a *massive* network of sites.\n\n-----------------------------------\n\nJust thought I\'d put this out there. I\'m sure it\'s not new to a lot of people, but at least to me it was interesting to see concepts like this actually put into practice on such a large scale. \n\n-----------------------------\n\nPS: I did a quick survey across several thousand domains, and for the record: right now, the most common external resource locations on the internet are(Google owned is bolded):\n\n**www.google-analytics.com**\n\n**pagead2.googlesyndication.com**\n\n**googleads.g.doubleclick.net**\n\nedge.quantserve.com\n\n**ad.doubleclick.net**\n\n**www.youtube.com**\n\nb.scorecardresearch.com\n\ns0.2mdn.net\n\ndg.specificclick.net\n\nview.atdmt.com\n\n**www.google.com**\n\n**ajax.googleapis.com**\n\n**partner.googleadservices.com**\n\nThat\'s a lot of data.',
 'DotCed,a Functional Analytics Consultant, offering Google Analytics Tagging, Reporting, Analysis, Strategy, SEO Auditing, and SEM Optimization. Call 919-404-9233 for a 15 min consultation.',
 'Here is the program details of the data analytics certification course at the Academy for Decision Science Ahmedabad.',
 'i decided grad school (physics) was not for me and i am branching out into the job market.  a web analytics place is interested in me (and i\'m interested in any kind of data analysis).  "The exercise is to use a comparison of three or more months of data to prepare a 5 to 10 slide PowerPoint presentation of any significant information about site visitors, what they are doing, how they arrive at our site that we could use to improve site performance as an acquisition source."  he said i should \'tell a story\'.  this is a field i am unfamiliar with so i\'m looking for any basic tips, common pitfalls, and expectations.  thanks.  (i am quite familiar with data analysis in general)',
 'Data Analytics provides an insight on the interpretation of data upon which a company can base their strategic plans and operational policies.',
 'Dieser Artikel soll weniger die Leistung oder die Genauigkeit einzelner Tools beleuchten, sondern viel eher aufzeigen, in wie weit Analysen voneinander abweichen können. Umso wichtiger ist es, sich bei einem Bedarf an solchen Controlling-Instrumenten bereits im Vorfeld Gedanken über etwaige KPIs zu machen um die richtigen Dinge richtig zu messen.',
 "http://i.imgur.com/maV1M.png\nFor no apparent reason I've had a (relatively) huge spike in traffic that has all come directly to my site. Most of my traffic before tended to be from stumbleupon and other referring sites, but I've had about 7k of direct hits on top of the roughly steady 1k a day I was getting.\nAny ideas?",
 "Anyone have any experience with this?  I have a client asking about it and the few implementations I've seen definitely don't provide the info I'm looking for. \n\nDoes anyone know if you can correlate the DFA info to segment users? Seems like you should, but haven't seen it done!",
 'Hey all, my gf is having trouble with GA and hasn\'t gotten any response in 3 days from posting in the Google help forums, so I figure I\'d try here. Question as follows:\n\n"I have a client that we coded a website for and Google analytics was plugged into it.  We would like to look at the statistics for the site, and no one can identify what account is associated with the tracking code that is embedded.\n\nI have pulled the user account number from the source code, I\'m just not sure how to identify what the login associated with it is.\n\nCan anyone help?   This is a fairly urgent request."\n\nThanks in advance for any help!',
 'I am a recent graduate with a BBA (marketing concentration) and was wondering how to enter this job market? I have zero professional experience with analytic work and entry level jobs all require at least one year of professional experience.\n\nI am familiar with Google Analytics and have professional experience involving finance, IT, and customer service functions. Should I work on certifications, return to school, or just keep looking?',
 'I was just wondering if I saw this code on a website, if it meant anything. Do all adword accounts use the same thing?',
 'anyone else have issues with the "include subdirectories" option in profile filters?  For some reason the results were way off for me; my solution was to use custom URI filters to get data accurately, but curious if anyone can explain this discrepancy and/or how i\'m mis-interpreting the Include Subdirectories option!!',
 "Is there anything I can do? The answers I'm seeing on google is no... c\nDoes any one know anything otherwise",
 "I've noticed that there are a lot of high ranking Russian, Spanish, etc sites that have a lot of followers. How can I find these sites, other than the few that I already know about? With Technorati I can search by popular, but they don't include non-English sites. ",
 "I applied for an analytic job and they sent me some homework to complete. I have been zooming through it until I reached a part that asked me to just analyze a document. I don't have access to SPSS and was wondering what I should do.\n\nI am trying to start in the analytic world and could really use some help!",
 "They want me to bring a sample Analytics report showing funnels and goals and provide observations and actionable insights on how I'd increase the conversion rate.\n\nThe problem is, I've only used Google Analytics on my own content based websites and have never had the need to setup any goals.\n\nI am scouring the web to find some sample reports that I can analyze, but I am having no luck.\n\nDoes anybody have any advice on how I can properly prepare for this given my current situation?",
 'What are your suggestions on tracking listing impressions on a page?  I have a category that displays various listings depending on a users geographic location.  I would like to track how many times a listing is shown.  Currently we are using Google analytics across the site and would like to use the Google Analytics API to track these listings.  Do you recommend custom event, page tracking, or creating a custom solution?  Thanks!',
 'PM me! I already have all the hitting and pitching data for 2009 in a clean format.',
 "First off, I don't claim to be a Google analytics expert. I'm using it to look at our organisations' site's unique visitor traffic over a three month period. When I look at in in a month-to-month view, there are gains in each month. When I look at the combined three-month view, there's a drop. I'm not doubting it's right, I'm just wondering what's going on.\n\nCan anyone offer a 'like I'm 5' explanation?\n\nAbsolute Unique Visitors: March - May\n1 March - 31 May 2011:\t200,365\n1 March - 31 May 2010:\t837,827\nChange:\t\t\t\t-76.09\n\n\nBy the month\nMarch:\n2011:\t\t104,716\n2010: \t\t89,517\nChange:    \t+16.98\n\nApril:\n2011:\t\t60,989\n2010: \t\t60,188\nChange:     \t+1.33\n\nMay:\n2011:\t\t99,639\n2010: \t\t87,864\nChange:\t       +13.40",
 "Hi,\n\nI'm the moderator of [/r/stopdrinking](http://www.reddit.com/r/stopdrinking), which is a community that helps people who are looking to control or quit their problem drinking.\n\nI'm interested in leanring more about the community that's gathered there, so we can build a subreddit that better meets the needs of its users.\n\nIs there any way to use google analytics to measure traffic on a subreddit? How would I go about doing that? \n\nThanks very much for your help!\n\n-Franks2000inchTV",
 "I have a client that wants to know the CTR on one of the ads they have running my mailing. I've told them it would be simplest if they just monitored all incoming traffic from my domain in their analytics, but I think they're technologically retarded, so they've asked us to provide the number of clicks for them.\n\nHere's my problem: the ad/transition page only shows up for clicks from my e-newsletter, and each link is built in HTML with a different URL (they all begin the same, but link to different articles or sites, so the code is different for each one). I pasted the GA code into each transition page, but, I can't seem to find the number of times a link is clicked on those pages. \n\nAnd then it leads to a second problem: I would have to check each piece of content each day to check for links.\n\nThere has to be an easier way! The internet proved no luck, affiliate marketer friends had no knowledge, so I'm bringing the question to you.\n\n\n**Is there a way to track clicks of a single URL leading away from multiple pages that my code is in?** And if so, tell me tell me tell me.",
 "Is there an Omniture debugger/tester that crawls the entire site?  I'm looking for something that will crawl and scan the entire code and identify all the Omniture tags on a site.  I've been using httpfox, which is great, but it requires me to click on each individual link and I'm looking for a more efficient process.\n\nThanks!",
 "I am trying to set up conversion tracking on a new website. The traffic will be landing on example.com, but the final step of the transaction takes place on app.example.com. This is the first time I have ever done something like this and Google's documentation does not have a lot of details about how to do this in GA.\n\n1) Does the tracking code need to be installed on example.com and app.example.com?\n\n2) when setting up the goal page does it need to be /landing-page/thank-you or app.example.com/landing-page/thank-you\n\n3) is this well documented in google's help finals and i am just calling it the wrong thing?",
 'If you want to be able to checkup on your site or blog stats anytime, anywhere, this app will give you quick access to the data you need to know...and more. ',
 'What is the difference between first click conversion, last interaction conversion and goal completions? I have 3 different numbers in my analytics.',
 'I have a traffic network of several different sites and I would like to compare data like bounce rate, time on site, similar goals etc. across these sites which are all set up under the same GA account.\n\nIs there a way I can compare these different data from different profiles in one combined profile so I can avoid jumping from one profile to another to compare this data ?\n\nI was looking into choosing the setting "Tracking multiple domains" but that does not seem give the feature to compare data between different sites but more track users across several domains.\n\nAny tips or links to a solution to this problem would be greatly appreciated.',
 "I'm a student but will soon be graduating and looking for a job in web analytics. Does anyone know how to get training in SiteCatalyst? Can I, as an individual, get online training away from an office? The Omniture site isn't very clear on this issue. Thanks! ",
 'I have analytics on my pages in wordpress. the issue is that the form that I use to collect leads is php, so the url doesnt change, the form and the success page are the same. \n\nHow can I track these leads using adwords and analytics? ',
 "For an ecommerce site I'm working on, I've made a new search inspired by Facebook's autosuggest search. When you start typing, the server will run a query, returning the top 8 matches in a list of links like the ones shown in Facebook. The user can then either click on one of the results, keep typing, or press enter/search to go to the full results page.  \n\nHere's what I want to track:  \n1) The percentage of users who go to one of the autosuggest search results, and what each user was searching for.  \n2) The percentage of users who go to the results page and then click  a product link, and what each user was searching for.  \n3) The percentage of users who go to the results page and then don't click anything, and what each user was searching for.  \n4) The percentage of users who go to the results page and get zero hits, and what each user was searching for.  \n\nIs this possible to do, and if so, how? Have I forgotten anything that's useful to track? I was thinking maybe the percentage of people who go to a product and end up putting it in the shopping cart and/or buying it, comparing buy rates and which products they buy between customers who come via the autosuggest page and those who come via the full search page. Would that be possible?\n",
 'I have the accounts UA id but I think the whole profile was deleted by an admin. Is there any test I can do to see if the account still exists? We have a lot of email accounts it could be hiding in.\n',
 'Anyone know how to link in the NEW interface ',
 'Greetings,\n\nI\'m trying to configure GA for a business that uses "yahoo small business" hosting and store.  They use their own domain for the store, but when someone wants to check out, it moves domains to yahoo\'s servers.  Is it possible to track the cart in the same GA account? Right now we have no goals working. \n\nDo I need to make a separate account for yahoo\'s cart domain? It also changes from unsecured to secured during checkout, I\'m not sure if this will affect the setup either.\n\nThanks for any help guys!\n\nTLDR - http://www.store.com &gt; https://www.store.yahoo.net Wat do?',
 'Hi,\n\nAre there any go to programming languages that someone should learn for when working in analytics?',
 'Hello,\nMy name is Joseph and I work for AREA203, a digital marketing agency in Chattanooga, Tennessee. We have a fun, casual work environment and Chattanooga is a beautiful area with a very low cost of living. We are currently building an analytics team to support our rapidly growing business. We offer relocation assistance and great benefits.\n\nRight now we need the following people for our analytics team:\nDigital Analyst II, \nSenior Digital Analyst, \nAffiliate Marketing Analyst II,\nSite Optimization Analyst (really cool new lab for this person!).\n\nWe are moving to a new building in town (we outgrew our current one) and the work environment is very modern, artistic, fun and awesome!\n\nIf you are interested in learning about any of these positions, please email me: joseph.cain@area203.com',
 'Hi all,\n\nI want to be able to track when someone clicks the "submit" button on my contact form and it looks like I should be able to do this with a GA goal event. Does anyone know how to do this or maybe a good tutorial on the subject? \n\nThanks.',
 'I find all kinds of different explanations.\n\nI know what the difference is between unique and non-unique and between visits and visitor.\n\nThe problem is "unique visits" and "unique visitors" is practically the same but not quite.\n\nWho can help?',
 'Is it possible to do A/B split testing with two versions of a Wordpress page? Has anyone got any experience with this?\n\n\nThanks',
 'Just would like to hear some insights about the job, the career and everything around it...\nLinks to where analytics-people gather are obviously welcome as well.',
 "So in May, a few of my sites are starting to show their own domain name as referral source, especially one of them that started doing it mid-May all of a sudden and already showing 14K visits from it. All sites have proper 301 set up in htaccess file from non www to www version. I really can't see why this is happening. Any ideas?",
 'I am trying to get my organisation in the habit of using GA campaign links on all print publicity, social media links and ads. \n\nSome of the urls (for print and social media) will need to go through a 301 redirect or a shortening services they are short enough to type. I have a Google spreadsheet that auto creates the campaign URLs but I am wondering how you guys create, store and manage the shorter link versions?\n\nDo you just use 301 redirects?\nDo you use a third party or a hosted service?',
 'To track Yahoo Search marketing &amp; Microsoft adcenter in Google Analytics all you have to do is to use Google Analytics URL Builder from there you will be able to track the result.\n\nFor Yahoo Search Marketing in Google Analytics\n\nStep 1) Website url ==&gt; place your website url\n\nStep 2)\n\nCampaign Source :- yahoo\ncampaign Medium :- cpc\ncampaign term :- {OVKEY} (for yahoo only)\nCamplign Content :- my ad group\nCampaign Name :- what tou want\n\nStep 3\nclick on generate URL\n\nClick Generate URL then copy &amp; paste this into the Destination URL field when you create an ad in YSM as seen below.\n\n\nFor Microsoft adCenter in Google Analytics\n\nStep 1) Website url ==&gt; place your website url\n\nStep 2)\n\nCampaign Source :- yahoo\ncampaign Medium :- cpc\ncampaign term :- {OrderItemId} (for Microsoft only)\nCamplign Content :- my ad group\nCampaign Name :- what tou want\n\nStep 3\nclick on generate URL\n\nClick Generate URL then copy &amp; paste this into the Destination URL field when you create an ad in Microsoft adcenter as seen below.',
 "... is this possible or do I have to create a custom report and drop it on the dashboard?\n\nSee -http://imgur.com/d7LbG - can I place 'Adcentre' or 'Bing' as  amenu item under 'Adwords'?\n\nIf not, is it possible torecreate the sections in 'Adwords', see here - http://imgur.com/RIl4s - in a custom report?\n\nEDIT: title should read 'Adcentre / Bing...'\n\nThanks\n",
 'One of the key reporting metrics returned by website analytics programs such as Google Analytics and Comscore is referral data.',

In [9]:
data.post.str.contains("<")

0         False
1         False
2         False
3         False
4         False
          ...
274234    False
274235    False
274236    False
274237    False
274238    False
Name: post, Length: 274239, dtype: object

In [10]:
# Rellemos los valores faltantes con una oración por defecto

data.post.fillna("Sin contenido", inplace=True)

In [11]:
# Comprobación de etiquetas HTML

data.post[data.post.str.contains("<")].tolist()

['I have just recently begun studying Deep Learning and also have no previous experience with TensorFlow. I am very confident in my understanding of the theoretical side of Neural Networks and have written a couple of very simple RNNs from scratch. I have now started to become familiar with using TensorFlow and have been trying to implement slightly more advanced NNs using it.\r\n\r\nCurrently, I am writing an LSTM that reads sequences of characters from a text, character-by-character, and then (hopefully) learns to accurately predict the next character. I encoded each character in the vocab as a one-hot vector of length equal to the size of the vocab, and the 1 represents the key to that character in my `int : char` map. The model takes as input `n` batches (100 in the example) of `m` character input and label sequences (25 in the example). These input sequences are just any random sequence of `m` characters from the first 80% of the text, the labels are the same sequences, but shifted one character forward. The last 20% is then used for validating the model\'s accuracy after it has been trained.\r\n\r\nIt can train itself to over 90% accuracy over 10,000 iterations of 100 batches of 25 character sequences, and and slightly lower level of accuracy on the unseen 20%  of the text (unless there are errors in my model somewhere).\r\n\r\nI am now attempting to allow my model to generate its own text after it has been trained. You will see my attempt at the bottom of my code. This is completely wrong as it is still takes in sequences of length 25, predicts the next 25 characters, and then uses this sequence of 25 predicted characters as the next input. Therefore, each time it is still only shifting along by one character and so each sequence it produces is nearly identical.\r\n\r\nIn order to correct this, I need my model to still train itself with the `m` length sequences, but then in the generating stage it must just take one character as input, predict the next character, and then use this predicted character as the next input. To do this, I will need to adjust my TensorFlow graph so that the `sequenceLength` variable used throughout is implemented using a `placeholder` instead of a fixed integer. That way, I will be able to set `sequenceLength` to 25 when training, and 1 when generating.\r\n\r\nI did something similar with the `batchSz` placeholder, but I cannot seem to reproduce something similar for `sequenceLength`.\r\n\r\n    from __future__ import print_function\r\n    import tensorflow as tf\r\n    from tensorflow.contrib import rnn\r\n    import numpy as np\r\n    import random\r\n\r\n    text = open("/home/kev/Documents/NeuralNetworks/CharacterPredicter/input.txt", \'r\').read()\r\n    #text = "abcdefghi"\r\n    vocab = list(set(text))\r\n    textSize = len(text)\r\n    vocabSize = len(vocab)\r\n    testingStartChar = int(textSize * 0.8)\r\n\r\n    charToInt = {char : i for i, char in enumerate(vocab)}\r\n    intToChar = {i : char for i, char in enumerate(vocab)}\r\n\r\n    sequenceLength = 25  # Must be strictly < (textSize / 5)\r\n    trainingIterations = 10000\r\n    batchSize = 100\r\n    numTestingSequences = int((textSize - testingStartChar - 1) / sequenceLength)\r\n\r\n    hiddenDimension = 100\r\n    learningRate = 0.01\r\n    forgetRate = 1.0\r\n    printStep = 1000\r\n\r\n    # Returns two 3D arrays of shape (batchSize x seqLength x vocabSize)\r\n    def generateData(batchSize, seqLength, isTraining):\r\n        inputs = []                                                 # e.g.  a, b = generateData(2, 3, True)\r\n        labels = []\r\n        charPointer = testingStartChar                              #       a -> [[[0, 1, ..., 0], [1, 0, ..., 0], [0, 0, ..., 1]]\r\n        for _ in range(batchSize):                                  #             [[1, 0, ..., 0], [0, 0, ..., 1], [0, 1, ..., 0]]]\r\n            inputSequence = []\r\n            labelSequence = []\r\n            if isTraining:\r\n                charPointer = random.randint(0, testingStartChar - seqLength)\r\n            for _ in range(seqLength):\r\n                oneHotInput = charToOneHot(text[charPointer])\r\n                oneHotLabel = charToOneHot(text[charPointer + 1])\r\n                inputSequence.append(oneHotInput)\r\n                labelSequence.append(oneHotLabel)\r\n                charPointer += 1\r\n            inputs.append(inputSequence)\r\n            labels.append(labelSequence)\r\n        return inputs, labels\r\n\r\n    # Takes in a single character and returns its corresponding\r\n    # one-hot vector of length vocabSize\r\n    def charToOneHot(char):\r\n        oneHot = [0] * vocabSize\r\n        oneHot[charToInt[char]] = 1\r\n        return oneHot\r\n\r\n    # Takes in a one-hot vector and returns its corresponding char\r\n    def oneHotToChar(oneHot):\r\n        charIndex = np.argmax(oneHot)\r\n        return intToChar[charIndex]\r\n\r\n    # Takes in a 3D array (last axis is one-hot vectors) and returns\r\n    # an array of the corresponding strings per row (batchSize)\r\n    # (Used for printing outputs)\r\n    def oneHotsToChars(array):                                          # e.g. [[[0, 1, ..., 0], [1, 0, ..., 0], [0, 0, ..., 1]],\r\n        chars = []                                                      #       [[1, 0, ..., 0], [0, 0, ..., 1], [0, 1, ..., 0]]]\r\n        for batchIndex in range(len(array)):\r\n            batchChars = ""                                             # ->   [\'hpb\',\r\n            for oneHotIndex in range(len(array[batchIndex])):           #      \'pbh\']\r\n                batchChars += oneHotToChar(array[batchIndex][oneHotIndex])\r\n            chars.append(batchChars)\r\n        return chars\r\n\r\n    # Takes a 3D array of real numbers (batchSize x sequenceLength x vocabSize)\r\n    # and returns a 3D array with the last axis being one-hot vectors\r\n    # corresponding to the real number of the highest value\r\n    def predictionToOneHots(prediction):\r\n        oneHots = []\r\n        for batchIndex in range(len(prediction)):\r\n            batchOneHots = []\r\n            for charArrayIndex in range(len(prediction[batchIndex])):\r\n                charArray = prediction[batchIndex][charArrayIndex]\r\n                charOneHot = [0] * len(charArray)\r\n                charIndex = np.argmax(charArray)\r\n                charOneHot[charIndex] = 1\r\n                batchOneHots.append(charOneHot)\r\n            oneHots.append(batchOneHots)\r\n        return oneHots\r\n\r\n    batchSz = tf.placeholder(tf.int32, shape=())\r\n    x = tf.placeholder(tf.float32, [None, sequenceLength, vocabSize])\r\n    y = tf.placeholder(tf.float32, [None, sequenceLength, vocabSize])\r\n    xFlat = tf.contrib.layers.flatten(x)                                                # [batchSize, sequenceLength*vocabSize]\r\n\r\n    W = tf.Variable(tf.random_normal([hiddenDimension, sequenceLength, vocabSize]))\r\n    b = tf.Variable(tf.random_normal([1, sequenceLength, vocabSize]))\r\n    WFlat = tf.contrib.layers.flatten(W)                                                # [hiddenDimension, sequenceLength*vocabSize]\r\n    bFlat = tf.contrib.layers.flatten(b)                                                # [1, sequenceLength*vocabSize]\r\n\r\n    cell = rnn.BasicLSTMCell(hiddenDimension, forget_bias=forgetRate)\r\n    outputs, states = tf.nn.static_rnn(cell, [xFlat], dtype=tf.float32)                 # outputs    = [[batchSize, hiddenDimension]]\r\n    predictionFlat = tf.add(tf.matmul(outputs[0], WFlat), bFlat)                        # outputs[0] = [batchSize, hiddenDimension]\r\n    prediction = tf.reshape(predictionFlat, [batchSz, sequenceLength, vocabSize])\r\n\r\n    # 2D array corresponding to whether character per sequence per batch was predicted correctly\r\n    # A correct prediction is when the highest predicted value is the same index as the 1 of the one-hot label\r\n    correctPrediction = tf.equal(tf.argmax(prediction, axis=2), tf.argmax(y, axis=2))   # [batchSize, sequenceLength]\r\n    accuracy = tf.reduce_mean(tf.cast(correctPrediction, tf.float32))\r\n\r\n    loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits=prediction, labels=y))\r\n    optimiser = tf.train.AdamOptimizer(learning_rate=learningRate).minimize(loss)\r\n\r\n    with tf.Session() as session:\r\n        session.run(tf.global_variables_initializer())\r\n\r\n        ############################################################################\r\n        #   TRAINING\r\n        ############################################################################\r\n        for iteration in range(trainingIterations):\r\n            batchX, batchY = generateData(batchSize, sequenceLength, isTraining=True)\r\n            dict = {batchSz: batchSize, x: batchX, y: batchY}\r\n            session.run(optimiser, dict)\r\n            if (iteration + 1) % printStep == 0 or iteration in (0, trainingIterations - 1):\r\n                batchAccuracy = session.run(accuracy, dict)\r\n                batchLoss  = session.run(loss, dict)\r\n                # inputOneHots = session.run(x, dict)\r\n                # labelOneHots = session.run(y, dict)\r\n                # predictions = session.run(prediction, dict)\r\n                # correctPredictions = session.run(correctPrediction, dict)\r\n                print("Iteration:\\t" + str(iteration + 1))\r\n                print("Accuracy:\\t" + str("%.2f" % (batchAccuracy * 100) + "%"))\r\n                print("Loss:\\t\\t" + str(batchLoss) + "\\n")\r\n                # print("Inputs:\\n" + str(oneHotsToChars(inputOneHots)) + "\\n")\r\n                # print("Labels:\\n" + str(oneHotsToChars(labelOneHots)) + "\\n")\r\n                # print("Prediction:\\n" + str(oneHotsToChars(predictionToOneHots(predictions))) + "\\n")\r\n                # print("Correct:\\n" + str(correctPredictions) + "\\n")\r\n\r\n        ############################################################################\r\n        #   TESTING\r\n        ############################################################################\r\n        testX, testY = generateData(numTestingSequences, sequenceLength, isTraining=False)\r\n        testAccuracy = session.run(accuracy, feed_dict={batchSz: numTestingSequences, x: testX, y: testY})\r\n        print("Testing Accuracy: " + str("%.2f" % (testAccuracy * 100) + "%"))\r\n\r\n        ############################################################################\r\n        #   GENERATING\r\n        ############################################################################\r\n        def stringToOneHots(string):\r\n            oneHots = []\r\n            for char in string:\r\n                oneHots.append(charToOneHot(char))\r\n            return oneHots\r\n\r\n        randIndex = random.randint(0, textSize - sequenceLength)\r\n        seedSequence = text[randIndex: randIndex + sequenceLength]\r\n        inputOneHots = stringToOneHots(seedSequence)\r\n\r\n        generatedText = ""\r\n        for _ in range(100):\r\n            dict = {x: [inputOneHots], batchSz: 1}\r\n            pred = session.run(prediction, dict)\r\n            predString = oneHotsToChars(predictionToOneHots(pred))[0]\r\n            inputOneHots = stringToOneHots(predString)\r\n            generatedText += predString\r\n\r\n        print(generatedText)\r\n\r\n\xa0\r\n\r\n*Side Notes:*\r\n\r\n1. If you uncomment all the `print` lines in the training loop, and reduce `sequenceLength` and `batchSize` to lower values, like 3, it is easier to follow exactly how the model works and what  outputs it produces at each stage.\r\n\r\n2. Is my method of initially keeping things in 3D arrays (batchSize x sequenceLength x vocabSize), and then flattening it all to be processed with TensorFlow ok? I find it easier to visualise all of the data in these dimensions, rather than having huge arrays of all the one-hot vectors concatenated into one. However, the code does get a bit messy by flattening everything, and then reshaping it all back into its original format. ',
 'Hi , I am learning ML , I have a few questions regarding regularized linear regression ,\n + should the features be scaled with 0 mean and unit variance ? And why ? \n + What is the significance of lambda , is the value of lambda specifies the bound of weights ? Ie Wi < 3/root(lambda) . \n',
 "I'm evaluating images on resnet using batches of 1 (there's a reason for that). I get ~50% GPU utilization. I believe the low utilization is because memory transfer takes too much time, but I don't know how I can find out exactly why GPU utilization is low. Can anyone give me any pointers on debugging GPUs like this? I have very little experience on this topic.\n\nEdit: I'm also at 280% CPU utilization. I'm slightly suspicious that I'm accidentally doing some work on the CPU, which might incur additional host<->device memory transfers.",
 "I am using an MLP to predict whether one of two teams who competed against each other will win said match. However, when I execute my TF graph, I'm getting 0% Loss and 100% Accuracy from the very start.\n\nI’ve based a lot of an [initial build](https://github.com/aadharna/Destiny/blob/master/TFTake1.ipynb) off of the [CIFAR-10 project I did](https://github.com/aadharna/CIFAR-10_ConvNet/blob/master/image_classification.ipynb), but adapted to my scenario of an MLP rather than a conv-net. \n\nTo make sure that the problem wasn't with my data (such as I included a feature which closely resembles the target) I spent yesterday testing around with different vertical slices of my data set. No matter what variables I input into the network, the result was always the same -- 0% Loss, 100% Accuracy. \n\nFurthermore, I spun up an simple SVM using sklearn with both the [rapid iteration data set](https://github.com/aadharna/Destiny/blob/master/testing_dataframe_205.csv) (first 1000 lines of the full dataset) and the full data set and ended up with 91% accuracy and 92% accuracy respectively.\n\nThis tells me that my problem is not with my data set but instead with TF and my neural network. To further confirm this, [I put together a NN using Keras](https://github.com/aadharna/Destiny/blob/master/KerasNN.ipynb) and got good results (94.8% Accuracy; 12.1% Loss).\n\nDetails about the data set: \n\nI have a 17 individualized statistics for each person who participated in the match, and I've flattened my vectors to be match-specific. Meaning one line of my CSV file is one match with form =: \n\n> <person0TeamAstats, person1TeamAstats, ..., person5TeamAstats, person0TeamBstats, ..., person5TeamBstats, targetVariable>\n\n\nEach row of my CSV has 205 statistics. Which, once the target Class is removed shrinks to 204 making each line a 1x204 vector. \n\n\nTherefore, I was hoping someone could take a look at my Tensorflow code and point me in the right direction.\n\nBest,\n\naadharna\n\nHopefully this question is more fitting than my last one which I asked at the very start of my project. ",
 'I know this might sound like a "google this for me question" but bare with me (I googled it). \n\nI\'m working with a highly imbalanced data set where the minority class accounts for 1.5%< of the total set. This leads to poor predictive performance by most models when nothing is done to address the problem because most algorithms will minimize cost on the majority class, to the detriment of the minority class, when training so as to decrease overall cost. \n\nSo far I\'ve tried out ANNs,RFs,XGBs, and SVMs and have found that XGB and RF outperform the others in this particular problem, so the remaining post will be about RF and XGB.\n\nI\'ve tried penalizing classification on the minority class much more than the majority class to try to fix the imbalance on an algorithmic level but I\'ve found undersampling and then training on the resulting data set to be more effective in my case. I\'ve also found the oversampling the minority and hybrid methods like SMOTE perform worse than undersampling.\n\nI was able to modify sklearns random forest classifier to undersample the data set at the tree level to minimize information loss and found it really helped. Before that, I was just undersampling the dataset and sending it through the algorithm so that n-trees trained on just 1 subsample of the dataset (with the modification, n-trees now train on n subsets of the dataset). \n\nI really want to do the same tweak on the XGBoost package but cannot seem to find where the heck XGBoost generates subsamples before training individual trees. \n\nDoes anybody know if this idea is doable? I found some more of less recent posts asking similar questions and finding that the typical response was "train a bunch of different XGBoosts and average their predictions." This answer is a little unsatisfying because it seems inefficient. ',
 'I know a T test can determine variability between data sets, and when I plug my data sets into the excel function "t-Test: Paired Two Sample for Means" IT gives me P(T<=t) less than 0.05 so my data sets are independent, I just don\'t know how it does it.\n\nAny advice on the mathematics behind Excel\'s function: "t-Test: Paired Two Sample for Means" would be greatly appreciated.',
 "I'm reading An Introduction to Generalized Linear Models by Dobson and Barnett.\n\nIn the introductory chapter, the authors describe a problem whereby they would like to test a hypothesis that males and females have similar growth rate during their gestational period.\n\nHere is some of the data.\n\n       age weight gender\n       <dbl>  <dbl>  <chr>\n     1    40   3126 Female\n     2    39   2817 Female\n     3    38   2795   Male\n     4    35   2925   Male\n     5    42   3210 Female\n     6    38   2991 Female\n     7    38   2975   Male\n     8    36   2412 Female\n     9    39   2875 Female\n    10    40   3317 Female\n\nThey authors want to fit something like\n\nY_j = a_j + beta age_ij \n\nAs you can see, the regressions have different intercepts but the same slope.  I'm hoping to recreate some of the results, but can't seem to fit this model in R.  Can someone point to a way to achieve this?",
 '[This blog here](http://data.princeton.edu/wws509/r/overdispersion.html) goes through examples of over-dispersion. I\'m a biologist so my stats knowledge could use some polishing; I don\'t quite follow their conclusion in the first example (A Poisson Model) where they write\n\n> mp <- glm(art~fem+mar+kid5+phd+ment, family=poisson, data=ab)\n\n> summary(mp)\n\nThey show the output and conclude "We can see that the model obviously doesn\'t fit the data".\n\nWhich part about that summary() output overtly indicates that the model doesn\'t fit the data?',
 "Hi folks, apologies if I'm asking this in the wrong place.\n\nSo I'm trying to mediation analysis using the PROCESS macro on a small dataset (n=25).\n\nWhen I ran a correlation matrix my mediator (SC) and dependent variable (A) were significantly correlated (r=-.46, p<.05) but when I ran the mediation analysis it looks like there is no effect (b=.15, p=.59). Does this make sense? Perhaps I am interpreting the output incorrectly..This is my first time using mediation analysis. Any help much appreciated!\n",

In [12]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string
import re
import contractions
import emoji

# Descargamos los recursos necesarios de NLTK
nltk.download("punkt", quiet=True)   # Tokenización
nltk.download("stopwords", quiet=True)   # Stopwords

# Definimos las expresión regulares
url_pattern = re.compile(r"http[s]?://\S+")
html_pattern = re.compile(r"<.*?>")

# Creamos un conjunto de stopwords en inglés para filtrar palabras comunes
stop_words = set(stopwords.words("english"))


# Función para convertir emojis a texto descriptivo
def convert_emojis_to_text(text):
    return emoji.demojize(text)


def preprocess_post(text: str):
    # Paso 1: Convertir todo el texto a minúsculas y resolver contracciones (como "I'm" a "I am")
    text = contractions.fix(text.lower())

    # Paso 2: Eliminar signos de puntuación y espacios extra
    text = text.translate(str.maketrans("", "", string.punctuation)).strip()

    # Paso 3: Eliminar URLs
    text = url_pattern.sub("", text)
    
    # Paso 4: Eliminar etiquetas HTML
    text = html_pattern.sub("", text)

    # Paso 5: Convertir los emojis en el texto a su representación textual (ej. ":smile:" en lugar de "😊")
    text = convert_emojis_to_text(text)

    # Paso 6: Tokenizar el texto, eliminar palabras que no sean alfabéticas y que sean stopwords
    sin_stopwords = [word for word in word_tokenize(text) if word.isalpha() and word not in stop_words]

    # Paso 7: Unir las palabras procesadas en un único string, separado por espacios
    clean_text = " ".join(sin_stopwords)

    return clean_text   # Devolver el texto limpio y preprocesado

In [13]:
# Aplicamos la función de preprocesado y normalización a cada uno de los posts y almacenos los resultados en una nueva columna llamada 'clean_post'

data["clean_post"] = data.post.apply(preprocess_post)

In [14]:
data.head()

,created_date,created_timestamp,subreddit,title,author,author_created_utc,full_link,score,num_comments,num_crossposts,subreddit_subscribers,post,sentiment,clean_post
0,2010-02-11 19:47:22,1265910442.0,analytics,So what do you guys all do related to analytic...,xtom,1.227476e+09,https://www.reddit.com/r/analytics/comments/b0...,7.0,4.0,0.0,NaN,There's a lot of reasons to want to know all t...,NEGATIVE,lot reasons want know stuff figured would get ...
1,2010-03-04 20:17:26,1267726646.0,analytics,"Google's Invasive, non-Anonymized Ad Targeting...",xtom,1.227476e+09,https://www.reddit.com/r/analytics/comments/b9...,2.0,1.0,0.0,NaN,"I'm cross posting this from /r/cyberlaw, hopef...",NEGATIVE,cross posting rcyberlaw hopefully guys find in...
2,2011-01-06 04:51:18,1294282278.0,analytics,"DotCed - Functional Web Analytics - Tagging, R...",dotced,1.294282e+09,https://www.reddit.com/r/analytics/comments/ew...,1.0,1.0,NaN,NaN,"DotCed,a Functional Analytics Consultant, offe...",NEGATIVE,dotceda functional analytics consultant offeri...
3,2011-01-19 11:45:30,1295430330.0,analytics,Program Details - Data Analytics Course,iqrconsulting,1.288245e+09,https://www.reddit.com/r/analytics/comments/f5...,0.0,0.0,NaN,NaN,Here is the program details of the data analyt...,NEGATIVE,program details data analytics certification c...
4,2011-01-19 21:52:28,1295466748.0,analytics,potential job in web analytics... need to anal...,therewontberiots,1.278672e+09,https://www.reddit.com/r/analytics/comments/f5...,2.0,4.0,NaN,NaN,i decided grad school (physics) was not for me...,POSITIVE,decided grad school physics branching job mark...

In [15]:
# data.to_csv("processed_dataset.csv")